name: Actions workflow

# events
on:
  push:
    branches: 
      - master
      # matches features/one-string
      - 'feature/*'
      # one * does not include several / we need **
      # matches feature/other/strings
      - 'feature/**'
      # use ! to exclude the branch
      - '!feature/feact'
    # we can use branches-ignore to ignore some branches but it can not be use at the same time as branches
    # branches-ignore:
    #   - ""
    # tags can also be use with patterns 
    tags:
      - v1.*
    # tags-ignore:
    # to run when a js file(s) is pushed
    paths:
      - '**.js'
      - '!filename.js'
    # paths-ignore:
  pull_request:
    types: [closed, assigned, opened, reopened]
    branches: 
      - master

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls
          echo $GITHUB_REF
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{ github.token }}
      # github action to clone your repo with the current commit
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files after checkout
        run: |
          pwd
          ls -a
      - name: Simple JS action
        id: greet
        # this could be a public github-user/repo@version|branch|commit
        # uses: actions/hello-wold-javascript-action@master
        # uses: actions/hello-wold-javascript-action@v1 versions follow the versioning conventions v1.1
        # uses: actions/hello-wold-javascript-action@commit-id
        uses: actions/hello-world-javascript-action@v1
        # to provide input to the action
        with:
          who-to-greet: Dany
      - name: Log Greeting time
        # access output from previous steps
        run: echo "${{ steps.greet.outputs.time }}"